# Generated by Django 4.1.1 on 2022-11-16 20:08

import chat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(null=True, upload_to=chat_app.models.chat_directory_path),
        ),
    ]
