# Generated by Django 4.1.1 on 2022-11-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
