# Generated by Django 4.1.1 on 2023-04-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatmessage_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatImage',
        ),
    ]
