# Generated by Django 4.1.1 on 2023-10-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_delete_chatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
