# Generated by Django 4.1.1 on 2022-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
