# Generated by Django 4.1.1 on 2023-10-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
