# Generated by Django 4.1.1 on 2023-08-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_comment_options_remove_post_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
