# Generated by Django 4.1.1 on 2023-10-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_remove_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
